export const INGREDIENT_CHANGED = 'INGREDIENT_CHANGED';
export const IS_PURCHASABLE = 'IS_PURCHASABLE';

export const PIZZA_ORDER_SUCCESS = 'PIZZA_ORDER_SUCCESS';
export const PIZZA_ORDER_FAIL = 'PIZZA_ORDER_FAIL';
export const PIZZA_ORDER_START = 'PIZZA_ORDER_START';
export const PIZZA_ORDERED_MODAL_CLOSED = 'PIZZA_ORDERED_MODAL_CLOSED';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';

export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';